RF:
    name: Random Forest Regressor
    regressor: RandomForestRegressor
    regressor_params:
        n_estimators: 100
        max_depth: 20 # null translates to None
        min_samples_split: 5
        n_jobs: -1
