RF:
    name: Random Forest Regressor
    regressor: RandomForestRegressor
    regressor_params:
        n_estimators: 100
        max_depth: 20
        min_samples_split: 5
        n_jobs: -1
    feature_selection_method: importance
    feature_selection_parameters:
        importance:
            method: importance
            min_importance: 0.005
    feature_reduction_method: None
    feature_reduction_parameters: {}

