GPR:
    name: Gaussian Process Regressor
    regressor: GaussianProcessRegressor
    regressor_params:
        normalize_y: True
        n_restarts_optimizer: 0
    feature_reduction_method: svd
    feature_reduction_parameters:
        svd:
            n_components: 8
