RF:
    name: Random Forest Regressor
    regressor: RandomForestRegressor
    regressor_params:
        random_state: 42
        n_jobs: -1
    feature_selection_method: None
    feature_selection_parameters: {}
    feature_reduction_method: None
    feature_reduction_parameters: {}
