RF:
    name: Random Forest Regressor
    regressor: RandomForestRegressor
    regressor_params:
        n_estimators: 40
        max_depth: 40
        min_samples_split: 14
        min_samples_leaf: 7
        max_features: 1 # max_features == n_features
        n_jobs: -1
    feature_selection_method: importance
    feature_selection_parameters:
        importance:
            method: importance
            min_importance: 0.05
    feature_reduction_method: None
    feature_reduction_parameters: {}
